sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - nightly
install: ./configure
before_script: ./tools/lint.sh
script: ./test
matrix:
    allow_failures:
        - python: nightly
