name: Tests

on: [push]


jobs:
  test:
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ matrix.python }}-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ matrix.python }}

      - name: Configure
        run: ./configure

      - name: Lint
        run: ./tools/lint.sh

      - name: Run tests
        run: ./test
